version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db:/app/db
    environment:
      - DJANGO_SETTINGS_MODULE=portfolio.settings
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/frontend
    environment:
      - NODE_ENV=production