version: '3.8'

services:
  web:
    build: .
    container_name: django-react-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./db:/app/db
    environment:
      - DJANGO_SETTINGS_MODULE=portfolio.settings
      - DJANGO_ENV=development
      - NODE_ENV=development
