# Generated by Django 4.1.4 on 2022-12-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skills_svg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='svg',
            new_name='link',
        ),
    ]
