# Generated by Django 4.1.4 on 2022-12-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_svg_skills_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
