# Generated by Django 4.1.4 on 2022-12-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_skills_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='category',
            field=models.CharField(choices=[('language', 'language'), ('framework', 'framework'), ('library', 'library'), ('other', 'other')], default='', max_length=20),
        ),
    ]
