# Generated by Django 4.1.4 on 2022-12-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_skills_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_time', models.CharField(default='', max_length=100)),
                ('cardTitle_company', models.CharField(default='', max_length=100)),
                ('cardSubtitle_position', models.CharField(default='', max_length=100)),
                ('cardDetailedText_description', models.TextField(default='')),
            ],
        ),
    ]
