# Generated by Django 4.1.4 on 2022-12-29 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_carddetailedtext_description_experience_carddetailedtext_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='cardDetailedText',
            new_name='cardDetailedText_description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='cardSubtitle',
            new_name='cardSubtitle_position',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='cardTitle',
            new_name='cardTitle_company',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='title',
            new_name='title_time',
        ),
    ]
