# Generated by Django 4.1.4 on 2022-12-31 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_posts_id_alter_posts_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='posts', serialize=False, to='api.projects'),
        ),
    ]
