# Generated by Django 4.1.4 on 2023-01-02 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_posts_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='posts', serialize=False, to='api.projects'),
        ),
    ]
