# Generated by Django 4.1.4 on 2023-01-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_posts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
