# Generated by Django 4.1.4 on 2023-01-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='active',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='github',
            field=models.TextField(blank=True, null=True),
        ),
    ]
