# Generated by Django 4.1.4 on 2023-07-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_posts_active_posts_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
