# Generated by Django 5.1.4 on 2025-02-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_posts_id_alter_posts_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='posts', to='api.projects'),
        ),
    ]
