name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/django-backend:latest .
          docker push ghcr.io/${{ github.repository_owner }}/django-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/react-frontend:latest -f frontend/Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/react-frontend:latest
